### ISSUE TITLE
[Brave websocket issue] Transaction detail page should go away

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#210]
The input modal of the transaction should go away after the transaction is successfully broadcasted.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/d2e3d54b-a121-4ae2-b54f-29cddb751699)

**Comment by kwunyeung** [comment]
The input modal of the transaction should go away after the transaction is successfully broadcasted.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/d2e3d54b-a121-4ae2-b54f-29cddb751699)

**Comment by calvinkei** [comment]
@kwunyeung is there any step to reproduce this? currently all modal will be closed after transaction is broadcasted

**Comment by calvinkei** [comment]
probably a brave browser websocket issue

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/210?planning-poker) with ZenHub @calvinkei

**Comment by calvinkei** [comment]
@kwunyeung  it turns out to be an issue on production
the chrome extension is loading iframe from staging.portal.forbole.com, which has different origin than x.forbole.com. as they are communicating using BroadcastChannel, it wont work with cross origin

i changed the iframe url on extension to be x.forbole.com as a fix. but in long term i will rewrite this to use another way for communication between extension and web since forbole x will be connected by different dapps in the future

please test with this extension
https://github.com/forbole/forbole-x/releases/download/v0.4.6/chrome-extension-v1.0.3.crx

**Comment by kwunyeung** [comment]
I will ask the infra team to rewrite everything from `staging.portal.forbole.com` to `x.forbole.com` for now.
