### ISSUE TITLE
Wrong data

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#268]
I have delegated different amount of DSM to 5 validators
but the percentage of asset  is the same.
![Screenshot 2021-09-07 at 2.40.15 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/4a1a2a04-13cf-4637-9392-41f17eaf4892)

**Comment by calvinkei** [comment]
@Rooty2020 the distribution is counted by USD value instead of number of tokens as you may be delegating different tokens (ATOM, DSM, AKT...) to the same validator. as the value of DSM is currently 0, the USD value will always be 0 no matter how much you delegate. so the percentage shown here will always be the same

in short, it will show the correct value once DSM's price is > $0

**Comment by Rooty2020** [comment]
@calvinkei 
ok, got it.
