### ISSUE TITLE
Asset Distribution by validators is wrong

### ISSUE THREAD

**Issue by RiccardoM** [forbole/forbole-x#399]
Inside the _Portfolio_ page, if I select the _by validators_ option of the _Asset distribution_ graph, I see that each validator has the same percentage associated to it. It appears that percentage is calculated as 

```
percentage = 100 / num_validators
```

Eg. I have delegate to 20 validators and each of them is showing 5% 

I believe it should instead be computed as 

```
percentage = tokens_delegated / total_tokens * 100%
```

**Comment by calvinkei** [comment]
@RiccardoM the percentage is based on the USD value of delegated tokens. As DSM's price is 0 now the percentage will always be equal among the validators

the reason for using USD value is if users delegate different tokens, say ATOM and DSM to the same validator, we cannot compare the token amount since their price is different

conclusion, this should be solved when DSM has non 0 price

**Comment by RiccardoM** [comment]
@calvinkei Than maybe it's better to indicate this somewhere, maybe with a :question: icon that describes this behavior?

**Comment by calvinkei** [comment]
@Rooty2020 any suggestion?
