### ISSUE TITLE
Rewards keep switching back to 0

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#503]
There are rewards in the account. And sometimes the UI would jump back to 0 DSM and then show the correct value again.
![image](https://user-images.githubusercontent.com/932636/145519649-231ca304-b217-46f0-910a-805b5dc96fb6.png)

**Comment by kanniec826** [comment]
@kwunyeung related to BDJuno Hasura

**Comment by RiccardoM** [comment]
@kanniec826 @calvinkei @kwunyeung This is not related only to BDJuno and/or Hasura. It's related to the fact that Forbole X uses a subscription to keep watching the rewards value and update them. What happens is the following: 

- Forbole X subscribes to Hasura
- When a new reward value is fetched from BDJuno, the existing  value is replaced inside the database
- During the replace, Hasura fires two events: the first one with an empty value and the second one with the updated value
- Since Forbole X is subscribing to events, it shows the updates every time 

This is due to the fact that in order to implement live queries, Hasura keeps constantly querying the database for new data and emits the result of the latest query (more details [here](https://hasura.io/docs/latest/graphql/core/databases/postgres/subscriptions/execution-and-performance.html)). What we could try to do is increasing the value of `HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_REFETCH_INTERVAL` to above 1 second, but I'm not sure it will work. 

Anyway, I think there is another problem inside Forbole X which is: it's using subscriptions even inside the withdraw rewards module. This makes the module continuously flickering due to the fact that rewards are constantly updating, which honestly gives me headache. I think it would be much better to use a query there instead @calvinkei

**Comment by calvinkei** [comment]
@RiccardoM when you say "which honestly gives me headache" do you mean it's affecting the server or you think the flickering number is an UX issue?

**Comment by RiccardoM** [comment]
> @RiccardoM when you say "which honestly gives me headache" do you mean it's affecting the server or you think the flickering number is an UX issue?

It's a UX issue: when I open the popup and it continuously update numbers I keep looking at it, which is distracting. I think that when you withdraw rewards you want to see fixed amount of DSM, not something that continues updating

**Comment by RiccardoM** [comment]
After 5 days, I'm back again on this issue. 

Unfortunately, there seems not to be an easy way of solving this from the side of BDJuno. The problem is that PostgreSQL does not allow concurrent `INSERT` statements on tables that rely on a `CONSTRAINT` (which is the case of all our tables actually). 

I've also tried incrementing the `HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_REFETCH_INTERVAL` time to 2 seconds (from the current 1) but that does not solve it either. And we can't make it smaller since it only accepts non-zero integers. 

So, what I propose we do to fix this @calvinkei is simply remove the `subscription` and make it a `query` inside the account details. This will grantee that the values do not change over time causing all sorts of problems.

**Comment by kwunyeung** [comment]
@calvinkei would it create too many https call if it's being changed to `query` with `pollInterval`?

**Comment by calvinkei** [comment]
if i query at a 3s interval i think it will be fine
