### ISSUE TITLE
Improving the error message when exceeding the ledger's withdrawal capacity

### ISSUE THREAD

**Issue by bragaz** [forbole/forbole-x#507]
After delegating to more than 20 validators, I tried to withdraw the rewards from all of them and the extension showed me a "connection refused from x.forbole.com" that, if inspected, was caused by a 520 server error.
<img width="524" alt="Schermata 2021-12-13 alle 10 17 59" src="https://user-images.githubusercontent.com/26248202/145786222-093dab72-6781-4f5b-b6a6-a36bc803202c.png">
I think it should be more explicit telling users why they're receiving that error.

**Comment by kwunyeung** [comment]
Does this only happen with Ledger? If so, should we limit the selection to be Max 20 if we know the account is from Ledger?

**Comment by RiccardoM** [comment]
@kwunyeung I confirm this happens when you delegate to more than the maximum amount of validators that the Ledger allows to withdraw with a single message, which is: 
- 3 validators if you are using a Ledger Nano S 
- 20 validators if you are using a Ledger Nano X 


After reducing the delegations to from 21 to 20 validators, it works properly. 

I think that to limit the selection you would also need to know the Ledger device they are using (since the limits are different as written inside Forbole X as well).

**Comment by kwunyeung** [comment]
There is a device id on Ledger. It's being returned when the device is being connected. We should be able to identify it's an S or X from it.

https://github.com/LedgerHQ/ledgerjs/blob/90360f1b00a11af4e64a7fc9d980a153ee6f092a/packages/react-native-hid/src/index.ts#L28

**Comment by bragaz** [comment]
@kwunyeung Yes limiting the selection would be a good design choice for this case

**Comment by calvinkei** [comment]
i found that the issue is not related to ledger withdraw limit, since it crashes on extension load instead of during tx signing. the issue is i am using the JSON string of tx data as query params in a web url, which exceeds the string length limit when you withdraw from > 20 validators. i will fix it by compressing the JSON string, otherwise the same will happen when you withdraw from >20 validators with recovery phrase
